

---
- hosts: localhost
  connection: local
  gather_facts: true
  tasks:
    #Creating fist app server
    - name: Create NIC
      azure_rm_networkinterface:
        resource_group: ansiproject
        name: testnic001
        virtual_network: testvn001
        subnet: subnet001
        security_group: secgroup001

    - name: Create virtual machine
      azure_rm_virtualmachine:
        resource_group: ansiproject
        name: testvm001
        vm_size: Standard_D1
        availability_set: dikavailabilityset
        managed_disk_type: Standard_LRS
        network_interfaces: testnic001
        admin_username: adminUser
        ssh_password_enabled: false
        ssh_public_keys:
            - path: /home/adminUser/.ssh/authorized_keys
              key_data: ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAi7/h2ir7zo6A/zgSM+4pE8Cm/0wU3J9G1bdiAAvX87B2qs0e8LLsaam1OHZ9Ck1sxjwOrCYLehkhnE56GepTLinErAUzJNN7Kt/eMmtVMt3ZYRplEHMmD9PnLL9hR7+j88ManAtxUh+DXtv2jiHZYS4rkanPu9eS9oKyOjoxr5IO7nIzSrUp7hR656Q/JwePhaopj+J5h4WB8F/dnwNZWKducAdXVuDnSisIxBOhicPdrl8ZZv2+gvmOlce8quvh13e7KmqdQG3ns6JmAmv+orFUWMc8046P7DT/30htubi0DpGgL4wOVEmVc6/XKXOF1Oczc2eaVh1v/4xhpagzxw== rsa-key-20190812
        image:
          offer: CentOS
          publisher: OpenLogic
          sku: '7.1'
          version: latest


    #Creating Second app server

    - name: Create NIC
      azure_rm_networkinterface:
        resource_group: ansiproject
        name: testnic002
        virtual_network: testvn001
        subnet: subnet001
        security_group: secgroup001

    - name: Create virtual machine
      azure_rm_virtualmachine:
        resource_group: ansiproject
        name: testvm002
        vm_size: Standard_D1
        availability_set: dikavailabilityset
        managed_disk_type: Standard_LRS
        network_interfaces: testnic002
        admin_username: adminUser
        ssh_password_enabled: false
        ssh_public_keys:
            - path: /home/adminUser/.ssh/authorized_keys
              key_data: ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAi7/h2ir7zo6A/zgSM+4pE8Cm/0wU3J9G1bdiAAvX87B2qs0e8LLsaam1OHZ9Ck1sxjwOrCYLehkhnE56GepTLinErAUzJNN7Kt/eMmtVMt3ZYRplEHMmD9PnLL9hR7+j88ManAtxUh+DXtv2jiHZYS4rkanPu9eS9oKyOjoxr5IO7nIzSrUp7hR656Q/JwePhaopj+J5h4WB8F/dnwNZWKducAdXVuDnSisIxBOhicPdrl8ZZv2+gvmOlce8quvh13e7KmqdQG3ns6JmAmv+orFUWMc8046P7DT/30htubi0DpGgL4wOVEmVc6/XKXOF1Oczc2eaVh1v/4xhpagzxw== rsa-key-20190812
        image:
          offer: CentOS
          publisher: OpenLogic
          sku: '7.1'
          version: latest

    #Creating Third app server
    
    - name: Create NIC
      azure_rm_networkinterface:
        resource_group: ansiproject
        name: testnic003
        virtual_network: testvn001
        subnet: subnet001
        security_group: secgroup001

    - name: Create virtual machine
      azure_rm_virtualmachine:
        resource_group: ansiproject
        name: testvm003
        vm_size: Standard_D1
        availability_set: dikavailabilityset
        managed_disk_type: Standard_LRS
        network_interfaces: testnic003
        admin_username: adminUser
        ssh_password_enabled: false
        ssh_public_keys:
            - path: /home/adminUser/.ssh/authorized_keys
              key_data: ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAi7/h2ir7zo6A/zgSM+4pE8Cm/0wU3J9G1bdiAAvX87B2qs0e8LLsaam1OHZ9Ck1sxjwOrCYLehkhnE56GepTLinErAUzJNN7Kt/eMmtVMt3ZYRplEHMmD9PnLL9hR7+j88ManAtxUh+DXtv2jiHZYS4rkanPu9eS9oKyOjoxr5IO7nIzSrUp7hR656Q/JwePhaopj+J5h4WB8F/dnwNZWKducAdXVuDnSisIxBOhicPdrl8ZZv2+gvmOlce8quvh13e7KmqdQG3ns6JmAmv+orFUWMc8046P7DT/30htubi0DpGgL4wOVEmVc6/XKXOF1Oczc2eaVh1v/4xhpagzxw== rsa-key-20190812
        image:
          offer: CentOS
          publisher: OpenLogic
          sku: '7.1'
          version: latest

    #Creating jump server
    
    - name: Create public ip
      azure_rm_publicipaddress:
        resource_group: ansiproject
        allocation_method: Dynamic
        name: jumpserverpip

    - name: Create NIC
      azure_rm_networkinterface:
        resource_group: ansiproject
        name: jumpservernic
        virtual_network: testvn001
        subnet: subnet001
        public_ip_name: jumpserverpip
        security_group: secgroup001

    - name: Create virtual machine
      azure_rm_virtualmachine:
        resource_group: ansiproject
        name: jumpserver
        vm_size: Standard_D1        
        managed_disk_type: Standard_LRS
        network_interfaces: jumpservernic
        admin_username: adminUser
        ssh_password_enabled: false
        ssh_public_keys:
            - path: /home/adminUser/.ssh/authorized_keys
              key_data: ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAi7/h2ir7zo6A/zgSM+4pE8Cm/0wU3J9G1bdiAAvX87B2qs0e8LLsaam1OHZ9Ck1sxjwOrCYLehkhnE56GepTLinErAUzJNN7Kt/eMmtVMt3ZYRplEHMmD9PnLL9hR7+j88ManAtxUh+DXtv2jiHZYS4rkanPu9eS9oKyOjoxr5IO7nIzSrUp7hR656Q/JwePhaopj+J5h4WB8F/dnwNZWKducAdXVuDnSisIxBOhicPdrl8ZZv2+gvmOlce8quvh13e7KmqdQG3ns6JmAmv+orFUWMc8046P7DT/30htubi0DpGgL4wOVEmVc6/XKXOF1Oczc2eaVh1v/4xhpagzxw== rsa-key-20190812
        image:
          offer: CentOS
          publisher: OpenLogic
          sku: '7.1'
          version: latest
