---
- hosts: localhost
  connection: local
  gather_facts: true
  tasks:
  - name: Create an availability set with advanced options
    azure_rm_availabilityset:
      name: dikavailabilityset
      location: eastus2
      resource_group: ansiproject
      platform_update_domain_count: 5
      platform_fault_domain_count: 3
      sku: Aligned
